import Foundation

// MARK: - Insight Models
//
// Unified model for insights generated by `InsightEngine`. Each insight has
// a `kind` (which drives the base wording and icon), an estimated `annualImpact`
// in EUR (= potential gain over 12 months), an `actionability` (1-5, higher
// = easier to apply) and a `confidence` (0-1 based on historical
// volume).
//
// `compositeScore` aggregates these 3 dimensions to allow ranking.

enum InsightKind: String, CaseIterable {
    /// A paid but long-unused subscription (= no non-recurring transaction
    /// associated with the merchant for N days).
    case dormantSubscription
    /// A daily/frequent habit with a low unit amount (coffee,
    /// snack, etc.) that becomes significant once accumulated.
    case smallFrequentHabit
    /// Several subscriptions of the same kind (video streaming, music, SaaS)
    /// active in parallel.
    case duplicateSubscriptions
    /// A category whose spending this month is significantly > the average
    /// of the previous 3 months (positive drift).
    case categoryDrift
    /// The category that accounts for most of the budget — useful to spell out
    /// "your biggest spending item is X (Y% of the total)".
    case topCategoryConcentration

    var systemIcon: String {
        switch self {
        case .dormantSubscription:        return "moon.zzz.fill"
        case .smallFrequentHabit:         return "cup.and.saucer.fill"
        case .duplicateSubscriptions:     return "rectangle.on.rectangle"
        case .categoryDrift:              return "arrow.up.right.circle.fill"
        case .topCategoryConcentration:   return "chart.pie.fill"
        }
    }

    /// Short label for the insight category (shown as the eyebrow).
    var label: String {
        switch self {
        case .dormantSubscription:        return "Abonnement dormant"
        case .smallFrequentHabit:         return "Habitude récurrente"
        case .duplicateSubscriptions:     return "Abonnements similaires"
        case .categoryDrift:              return "Dérive de catégorie"
        case .topCategoryConcentration:   return "Top dépenses"
        }
    }
}

struct Insight: Identifiable, Hashable {
    let id: String           // stable (= kind + reference) for SwiftUI diffing
    let kind: InsightKind
    /// A short title (max 1 line), ready to display. Base statistical wording
    /// — may be replaced by the LLM (Layer 3) in V2.
    let title: LocalizedStringResource
    /// Expanded detail (2-3 lines) with numbers and a concrete action.
    let detail: LocalizedStringResource
    /// Estimated potential annual gain (€). 0 if the insight is purely informational.
    let annualImpact: Double
    /// Feasibility 1-5. 5 = a trivial marginal change (1 tap), 1 = drastic.
    let actionability: Int
    /// Confidence 0-1 based on historical volume. Below 0.3 the insight
    /// is ignored (too little data to conclude anything).
    let confidence: Double

    /// A composite score for sorting. `annualImpact × actionability × confidence`
    /// — gives more weight to high-impact AND easy-to-apply actions.
    var compositeScore: Double {
        annualImpact * Double(actionability) * confidence
    }
    
    static func == (lhs: Insight, rhs: Insight) -> Bool {
        lhs.id == rhs.id
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }

    /// `true` if the insight has an actionable recommendation (vs. purely informational).
    var isActionable: Bool { annualImpact > 0 }
}
